# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from typing import (
    TYPE_CHECKING,
    Any,
    ClassVar,
    Dict,
    Optional,
    Type,
    TypeVar,
)

from typing_extensions import Literal

LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import actions, fields
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict
from ._types import FuncType

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseQuizAttempt(_PrismaModel):
    __prisma_model__: ClassVar[Literal['QuizAttempt']] = 'QuizAttempt'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.QuizAttemptActions[_PrismaModelT]':
        from .client import get_client

        return actions.QuizAttemptActions[_PrismaModelT](client or get_client(), cls)


class BaseQuestionResponse(_PrismaModel):
    __prisma_model__: ClassVar[Literal['QuestionResponse']] = 'QuestionResponse'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.QuestionResponseActions[_PrismaModelT]':
        from .client import get_client

        return actions.QuestionResponseActions[_PrismaModelT](client or get_client(), cls)


class BaseTeacherActionPlan(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TeacherActionPlan']] = 'TeacherActionPlan'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TeacherActionPlanActions[_PrismaModelT]':
        from .client import get_client

        return actions.TeacherActionPlanActions[_PrismaModelT](client or get_client(), cls)


class BaseUploadedDocument(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UploadedDocument']] = 'UploadedDocument'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UploadedDocumentActions[_PrismaModelT]':
        from .client import get_client

        return actions.UploadedDocumentActions[_PrismaModelT](client or get_client(), cls)


class BaseStudyTwinMatch(_PrismaModel):
    __prisma_model__: ClassVar[Literal['StudyTwinMatch']] = 'StudyTwinMatch'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.StudyTwinMatchActions[_PrismaModelT]':
        from .client import get_client

        return actions.StudyTwinMatchActions[_PrismaModelT](client or get_client(), cls)
