# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking


LiteralString = str
# -- template http.py.jinja --
from ._sync_http import (
    HTTP as HTTP,
)
from ._sync_http import (
    Response as Response,
)
from ._sync_http import (
    client as client,
)
