# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking


LiteralString = str
# -- template partials.py.jinja --



# users can modify relational types which are then namespaced to partials.
# so we have to import ourselves in order to resolve forward references


# fmt: on
