"""Authoritative NCERT Chapter Concept Registry and Relationship Definitions.

Provides structured subtopic nodes, descriptions, sections, keywords, and
dependency edges for all 13 chapters of Class 9 and 13 chapters of Class 10 NCERT Science.
"""

from typing import Any, Dict, List, Optional


CHAPTER_CONCEPTS_REGISTRY: Dict[str, Dict[str, Any]] = {
    # =========================================================================
    # CLASS 10 NCERT SCIENCE CHAPTERS
    # =========================================================================
    "Chemical Reactions and Equations": {
        "class_level": 10,
        "chapter_number": 1,
        "nodes": [
            {
                "id": "chem_reaction_characteristics",
                "name": "Chemical Equations & Balancing",
                "section": "1.1",
                "tier": 1,
                "description": "Law of conservation of mass, word equations, skeletal equations, and balancing chemical equations.",
                "keywords": ["chemical equation", "balancing", "reactants", "products", "conservation of mass", "skeletal equation"],
                "pos_x": 160,
                "pos_y": 120,
            },
            {
                "id": "chem_combination_decomposition",
                "name": "Combination & Decomposition",
                "section": "1.2.1 - 1.2.2",
                "tier": 2,
                "description": "Formation of single product from multiple reactants, and breakdown of compounds via thermal, electrolytic, and photolytic energy.",
                "keywords": ["combination reaction", "decomposition", "calcium oxide", "slaked lime", "electrolysis of water", "silver chloride"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "chem_displacement_reactions",
                "name": "Displacement & Double Displacement",
                "section": "1.2.3 - 1.2.4",
                "tier": 2,
                "description": "Reactivity-driven metal displacement and ion exchange reactions resulting in precipitates.",
                "keywords": ["displacement", "double displacement", "precipitate", "barium sulphate", "copper sulphate", "iron nail"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "chem_redox_reactions",
                "name": "Oxidation & Reduction (Redox)",
                "section": "1.2.5",
                "tier": 3,
                "description": "Gain or loss of oxygen and hydrogen, electron transfer concepts, and simultaneous oxidation-reduction.",
                "keywords": ["redox", "oxidation", "reduction", "oxidising agent", "reducing agent", "copper oxide"],
                "pos_x": 620,
                "pos_y": 140,
            },
            {
                "id": "chem_corrosion_rancidity",
                "name": "Corrosion & Rancidity",
                "section": "1.3",
                "tier": 3,
                "description": "Everyday effects of oxidation: rusting of iron, tarnishing of silver, and oxidation of fats and oils.",
                "keywords": ["corrosion", "rusting", "rancidity", "antioxidants", "nitrogen gas", "galvanisation"],
                "pos_x": 820,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "chem_reaction_characteristics", "target": "chem_combination_decomposition", "relationship": "prerequisite"},
            {"source": "chem_reaction_characteristics", "target": "chem_displacement_reactions", "relationship": "prerequisite"},
            {"source": "chem_combination_decomposition", "target": "chem_redox_reactions", "relationship": "related"},
            {"source": "chem_displacement_reactions", "target": "chem_redox_reactions", "relationship": "related"},
            {"source": "chem_redox_reactions", "target": "chem_corrosion_rancidity", "relationship": "derived_from"},
        ],
    },

    "Acids, Bases and Salts": {
        "class_level": 10,
        "chapter_number": 2,
        "nodes": [
            {
                "id": "acids_indicators_properties",
                "name": "Acid-Base Indicators & Properties",
                "section": "2.1",
                "tier": 1,
                "description": "Litmus, phenolphthalein, olfactory indicators, and chemical reactions of acids/bases with metals and carbonates.",
                "keywords": ["indicator", "litmus", "acid", "base", "metal reaction", "hydrogen gas", "carbon dioxide"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "acids_neutralisation_ions",
                "name": "H+ and OH- Ions in Solution",
                "section": "2.2",
                "tier": 2,
                "description": "Behavior of acids and bases in water: dissociation into hydronium (H3O+) and hydroxide (OH-) ions.",
                "keywords": ["hydronium ion", "hydroxide ion", "dissociation", "dilution", "exothermic", "neutralisation"],
                "pos_x": 380,
                "pos_y": 140,
            },
            {
                "id": "acids_ph_scale",
                "name": "pH Scale & Everyday Importance",
                "section": "2.3",
                "tier": 2,
                "description": "Universal indicator, hydrogen ion concentration measurement (0-14), tooth decay, soil pH, and acid rain.",
                "keywords": ["ph scale", "universal indicator", "acidic", "basic", "digestive system", "tooth decay", "acid rain"],
                "pos_x": 600,
                "pos_y": 80,
            },
            {
                "id": "acids_commercial_salts",
                "name": "Commercial Salts & Compounds",
                "section": "2.4",
                "tier": 3,
                "description": "Preparation, properties, and uses of Bleaching powder, Baking soda, Washing soda, and Plaster of Paris.",
                "keywords": ["baking soda", "washing soda", "bleaching powder", "plaster of paris", "chlor-alkali process", "water of crystallisation"],
                "pos_x": 600,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "acids_indicators_properties", "target": "acids_neutralisation_ions", "relationship": "prerequisite"},
            {"source": "acids_neutralisation_ions", "target": "acids_ph_scale", "relationship": "derived_from"},
            {"source": "acids_neutralisation_ions", "target": "acids_commercial_salts", "relationship": "related"},
            {"source": "acids_ph_scale", "target": "acids_commercial_salts", "relationship": "related"},
        ],
    },

    "Metals and Non-metals": {
        "class_level": 10,
        "chapter_number": 3,
        "nodes": [
            {
                "id": "metals_physical_chemical_props",
                "name": "Physical & Chemical Properties",
                "section": "3.1 - 3.2",
                "tier": 1,
                "description": "Malleability, ductility, conductivity, amphoteric oxides, and reactions with water, acids, and oxygen.",
                "keywords": ["malleability", "ductility", "amphoteric oxide", "metal reaction", "hydrogen", "reactivity"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "metals_reactivity_series",
                "name": "Reactivity Series & Ionic Bonding",
                "section": "3.2.5 - 3.3",
                "tier": 2,
                "description": "Arrangement of metals by decreasing reactivity and electron transfer forming ionic compounds (NaCl, MgCl2).",
                "keywords": ["reactivity series", "ionic bond", "electron transfer", "lattice", "electrovalent", "melting point"],
                "pos_x": 400,
                "pos_y": 140,
            },
            {
                "id": "metals_metallurgy_extraction",
                "name": "Metallurgy & Extraction",
                "section": "3.4",
                "tier": 3,
                "description": "Roasting, calcination, reduction of ores, electrolytic refining, and obtaining metals from low, medium, and high reactivity tiers.",
                "keywords": ["metallurgy", "roasting", "calcination", "electrolytic refining", "gangue", "thermite process"],
                "pos_x": 660,
                "pos_y": 80,
            },
            {
                "id": "metals_corrosion_alloys",
                "name": "Corrosion Prevention & Alloys",
                "section": "3.5",
                "tier": 3,
                "description": "Rust prevention via galvanising, anodising, and creation of homogeneous metal mixtures (brass, bronze, solder, stainless steel).",
                "keywords": ["galvanisation", "alloys", "brass", "bronze", "solder", "stainless steel", "amalgam"],
                "pos_x": 660,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "metals_physical_chemical_props", "target": "metals_reactivity_series", "relationship": "prerequisite"},
            {"source": "metals_reactivity_series", "target": "metals_metallurgy_extraction", "relationship": "derived_from"},
            {"source": "metals_reactivity_series", "target": "metals_corrosion_alloys", "relationship": "related"},
        ],
    },

    "Carbon and its Compounds": {
        "class_level": 10,
        "chapter_number": 4,
        "nodes": [
            {
                "id": "carbon_covalent_bonding",
                "name": "Covalent Bonding & Versatility",
                "section": "4.1 - 4.2",
                "tier": 1,
                "description": "Tetravalency, catenation, allotropes (diamond, graphite, fullerenes), and single/double/triple covalent electron sharing.",
                "keywords": ["covalent bond", "tetravalency", "catenation", "diamond", "graphite", "fullerene", "electron dot"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "carbon_hydrocarbons_homologous",
                "name": "Hydrocarbons & Homologous Series",
                "section": "4.2.2 - 4.2.5",
                "tier": 2,
                "description": "Alkanes, alkenes, alkynes, structural isomerism, functional groups (alcohol, aldehyde, ketone, carboxylic acid), and IUPAC naming.",
                "keywords": ["alkane", "alkene", "alkyne", "homologous series", "isomer", "functional group", "iupac"],
                "pos_x": 400,
                "pos_y": 140,
            },
            {
                "id": "carbon_chemical_reactions",
                "name": "Combustion, Oxidation & Addition",
                "section": "4.3",
                "tier": 3,
                "description": "Combustion, oxidation using alkaline KMnO4, substitution in alkanes, and hydrogenation addition reactions of unsaturated fats.",
                "keywords": ["combustion", "addition reaction", "substitution", "hydrogenation", "oxidising agent", "catalyst"],
                "pos_x": 660,
                "pos_y": 80,
            },
            {
                "id": "carbon_ethanol_ethanoic_soaps",
                "name": "Ethanol, Ethanoic Acid & Soaps",
                "section": "4.4 - 4.5",
                "tier": 3,
                "description": "Esterification, saponification, properties of ethanol and glacial acetic acid, and micelle formation in soap cleansing.",
                "keywords": ["ethanol", "ethanoic acid", "esterification", "saponification", "soap", "detergent", "micelle", "hard water"],
                "pos_x": 660,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "carbon_covalent_bonding", "target": "carbon_hydrocarbons_homologous", "relationship": "prerequisite"},
            {"source": "carbon_hydrocarbons_homologous", "target": "carbon_chemical_reactions", "relationship": "related"},
            {"source": "carbon_hydrocarbons_homologous", "target": "carbon_ethanol_ethanoic_soaps", "relationship": "derived_from"},
        ],
    },

    "Life Processes": {
        "class_level": 10,
        "chapter_number": 5,
        "nodes": [
            {
                "id": "bio_nutrition",
                "name": "Autotrophic & Heterotrophic Nutrition",
                "section": "5.2",
                "tier": 1,
                "description": "Photosynthesis equation, stomata, human alimentary canal, digestive enzymes (pepsin, trypsin, amylase), and peristalsis.",
                "keywords": ["nutrition", "photosynthesis", "stomata", "alimentary canal", "digestion", "pepsin", "trypsin", "bile", "villi"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "bio_respiration",
                "name": "Cellular Respiration & Gas Exchange",
                "section": "5.3",
                "tier": 2,
                "description": "Aerobic vs anaerobic breakdown of glucose, ATP synthesis, human alveoli, and breathing mechanism.",
                "keywords": ["respiration", "aerobic", "anaerobic", "glucose breakdown", "alveoli", "atp", "fermentation", "lactic acid"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "bio_transportation",
                "name": "Circulatory System & Plant Transport",
                "section": "5.4",
                "tier": 2,
                "description": "Human 4-chambered heart, double circulation, arteries/veins, xylem tracheids (water), and phloem translocation (food).",
                "keywords": ["heart", "double circulation", "blood", "xylem", "phloem", "transpiration", "translocation", "valves"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "bio_excretion",
                "name": "Excretory System & Nephron Function",
                "section": "5.5",
                "tier": 3,
                "description": "Kidney structure, nephron ultrafiltration, selective reabsorption of glucose/salts, tubular secretion, and dialysis.",
                "keywords": ["excretion", "kidney", "nephron", "bowman capsule", "glomerulus", "reabsorption", "urine formation", "dialysis"],
                "pos_x": 650,
                "pos_y": 160,
            },
        ],
        "edges": [
            {"source": "bio_nutrition", "target": "bio_respiration", "relationship": "prerequisite"},
            {"source": "bio_nutrition", "target": "bio_transportation", "relationship": "related"},
            {"source": "bio_transportation", "target": "bio_excretion", "relationship": "derived_from"},
            {"source": "bio_respiration", "target": "bio_excretion", "relationship": "related"},
        ],
    },

    "Control and Coordination": {
        "class_level": 10,
        "chapter_number": 6,
        "nodes": [
            {
                "id": "ctrl_neuron_reflex",
                "name": "Neuron Structure & Reflex Arc",
                "section": "6.1.1 - 6.1.2",
                "tier": 1,
                "description": "Dendrite, axon, synapse neurotransmitters, stimulus detection by receptors, and spinal reflex arc pathway.",
                "keywords": ["neuron", "axon", "synapse", "dendrite", "reflex arc", "reflex action", "spinal cord"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "ctrl_human_brain",
                "name": "Human Central Nervous System",
                "section": "6.1.3",
                "tier": 2,
                "description": "Forebrain (cerebrum), midbrain, and hindbrain (cerebellum, medulla, pons) controlling voluntary/involuntary actions.",
                "keywords": ["brain", "cerebrum", "cerebellum", "medulla", "cranium", "meninges", "voluntary action"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "ctrl_plant_movements",
                "name": "Plant Tropic & Nastic Movements",
                "section": "6.2",
                "tier": 2,
                "description": "Phototropism, geotropism, hydrotropism, chemotropism, and auxin-mediated directional growth responses.",
                "keywords": ["phototropism", "geotropism", "hydrotropism", "chemotropism", "auxin", "touch me not", "turgor"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "ctrl_hormones_endocrine",
                "name": "Endocrine Hormones & Feedback",
                "section": "6.3",
                "tier": 3,
                "description": "Plant hormones (gibberellin, cytokinin, ABA) and animal hormones (adrenaline, thyroxine, insulin, pituitary growth hormone).",
                "keywords": ["hormones", "endocrine", "insulin", "thyroxine", "adrenaline", "abscisic acid", "cytokinin", "feedback mechanism"],
                "pos_x": 650,
                "pos_y": 160,
            },
        ],
        "edges": [
            {"source": "ctrl_neuron_reflex", "target": "ctrl_human_brain", "relationship": "prerequisite"},
            {"source": "ctrl_neuron_reflex", "target": "ctrl_plant_movements", "relationship": "related"},
            {"source": "ctrl_human_brain", "target": "ctrl_hormones_endocrine", "relationship": "derived_from"},
            {"source": "ctrl_plant_movements", "target": "ctrl_hormones_endocrine", "relationship": "related"},
        ],
    },

    "How do Organisms Reproduce?": {
        "class_level": 10,
        "chapter_number": 7,
        "nodes": [
            {
                "id": "repro_dna_asexual",
                "name": "DNA Copying & Asexual Modes",
                "section": "7.1 - 7.2",
                "tier": 1,
                "description": "DNA replication, variation significance, fission (binary/multiple), fragmentation, regeneration, budding, and spore formation.",
                "keywords": ["dna copying", "variation", "binary fission", "budding", "regeneration", "fragmentation", "vegetative propagation"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "repro_flowering_plants",
                "name": "Sexual Reproduction in Plants",
                "section": "7.3.1",
                "tier": 2,
                "description": "Flower anatomy (stamen, carpel), pollination (self/cross), pollen tube growth, double fertilisation, and seed germination.",
                "keywords": ["flower", "stamen", "carpel", "pollination", "pollen tube", "fertilisation", "seed germination", "ovary"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "repro_human_systems",
                "name": "Human Male & Female Reproduction",
                "section": "7.3.2 - 7.3.3",
                "tier": 2,
                "description": "Puberty changes, testes/sperm, ovaries/ovum, fertilisation in fallopian tube, implantation, and placenta function.",
                "keywords": ["puberty", "testes", "ovary", "fallopian tube", "sperm", "placenta", "menstruation", "embryo"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "repro_reproductive_health",
                "name": "Reproductive Health & Contraception",
                "section": "7.4",
                "tier": 3,
                "description": "Sexually transmitted infections (STIs: HIV, gonorrhoea, warts) and barrier, chemical, IUD, and surgical contraceptive methods.",
                "keywords": ["reproductive health", "contraception", "condom", "iud", "copper t", "vasectomy", "tubectomy", "stis"],
                "pos_x": 650,
                "pos_y": 160,
            },
        ],
        "edges": [
            {"source": "repro_dna_asexual", "target": "repro_flowering_plants", "relationship": "prerequisite"},
            {"source": "repro_dna_asexual", "target": "repro_human_systems", "relationship": "prerequisite"},
            {"source": "repro_human_systems", "target": "repro_reproductive_health", "relationship": "derived_from"},
        ],
    },

    "Heredity": {
        "class_level": 10,
        "chapter_number": 8,
        "nodes": [
            {
                "id": "heredity_variations",
                "name": "Accumulation of Variations",
                "section": "8.1",
                "tier": 1,
                "description": "Origins of phenotypic variation in asexual vs sexual reproduction and survival advantages in changing environments.",
                "keywords": ["variation", "heredity", "traits", "environmental selection", "survival"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "heredity_mendel_laws",
                "name": "Mendelian Inheritance & Monohybrid Cross",
                "section": "8.2.1 - 8.2.2",
                "tier": 2,
                "description": "Mendel's experiments with garden peas: dominant vs recessive alleles, F1 and F2 generations, 3:1 phenotypic ratio.",
                "keywords": ["mendel", "monohybrid", "dominant", "recessive", "f1 generation", "f2 generation", "phenotype", "genotype"],
                "pos_x": 400,
                "pos_y": 80,
            },
            {
                "id": "heredity_dihybrid_expression",
                "name": "Dihybrid Cross & Gene Expression",
                "section": "8.2.3",
                "tier": 3,
                "description": "Independent inheritance of two separate traits (9:3:3:1 ratio) and protein synthesis mechanism of gene expression.",
                "keywords": ["dihybrid cross", "independent assortment", "9:3:3:1", "genes", "chromosomes", "protein synthesis"],
                "pos_x": 660,
                "pos_y": 80,
            },
            {
                "id": "heredity_sex_determination",
                "name": "Sex Determination in Humans",
                "section": "8.2.4",
                "tier": 2,
                "description": "Autosomes vs allosomes, XX and XY chromosome pairing, and equal 50% probability of male or female offspring.",
                "keywords": ["sex determination", "xx chromosomes", "xy chromosomes", "father genetic contribution", "allosomes"],
                "pos_x": 400,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "heredity_variations", "target": "heredity_mendel_laws", "relationship": "prerequisite"},
            {"source": "heredity_variations", "target": "heredity_sex_determination", "relationship": "related"},
            {"source": "heredity_mendel_laws", "target": "heredity_dihybrid_expression", "relationship": "derived_from"},
        ],
    },

    "Light – Reflection and Refraction": {
        "class_level": 10,
        "chapter_number": 9,
        "nodes": [
            {
                "id": "light_reflection_mirrors",
                "name": "Laws of Reflection & Spherical Mirrors",
                "section": "9.2.1 - 9.2.2",
                "tier": 1,
                "description": "Angle of incidence equals reflection, concave and convex mirrors, pole, center of curvature, focus, and focal length.",
                "keywords": ["reflection", "concave mirror", "convex mirror", "principal focus", "focal length", "center of curvature"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "light_mirror_formula",
                "name": "Mirror Formula & Magnification",
                "section": "9.2.3 - 9.2.4",
                "tier": 2,
                "description": "Sign convention, mirror equation 1/v + 1/u = 1/f, and linear magnification m = -v/u = h'/h.",
                "keywords": ["mirror formula", "sign convention", "magnification", "real image", "virtual image", "cartesian"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "light_refraction_snell",
                "name": "Refraction of Light & Snell's Law",
                "section": "9.3.1 - 9.3.2",
                "tier": 2,
                "description": "Bending of light across media, refractive index n = c/v, and Snell's Law sin(i)/sin(r) = constant.",
                "keywords": ["refraction", "snell law", "refractive index", "optical density", "speed of light", "glass slab"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "light_lenses_formula",
                "name": "Spherical Lenses & Lens Formula",
                "section": "9.3.3 - 9.3.5",
                "tier": 3,
                "description": "Convex and concave lens ray diagrams, lens equation 1/v - 1/u = 1/f, and optical power P = 1/f (Dioptres).",
                "keywords": ["lens formula", "convex lens", "concave lens", "optical power", "dioptre", "focal power"],
                "pos_x": 650,
                "pos_y": 160,
            },
        ],
        "edges": [
            {"source": "light_reflection_mirrors", "target": "light_mirror_formula", "relationship": "derived_from"},
            {"source": "light_reflection_mirrors", "target": "light_refraction_snell", "relationship": "related"},
            {"source": "light_refraction_snell", "target": "light_lenses_formula", "relationship": "prerequisite"},
            {"source": "light_mirror_formula", "target": "light_lenses_formula", "relationship": "related"},
        ],
    },

    "The Human Eye and the Colourful World": {
        "class_level": 10,
        "chapter_number": 10,
        "nodes": [
            {
                "id": "eye_anatomy_accommodation",
                "name": "Eye Anatomy & Power of Accommodation",
                "section": "10.1",
                "tier": 1,
                "description": "Cornea, pupil, iris, ciliary muscles adjusting lens curvature, near point (25 cm), and far point (infinity).",
                "keywords": ["human eye", "accommodation", "ciliary muscles", "retina", "cornea", "near point", "iris"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "eye_vision_defects",
                "name": "Defects of Vision & Correction",
                "section": "10.2",
                "tier": 2,
                "description": "Myopia (corrected by concave lens), Hypermetropia (convex lens), Presbyopia (bifocal lenses), and Astigmatism.",
                "keywords": ["myopia", "hypermetropia", "presbyopia", "corrective lens", "bifocal", "short sightedness"],
                "pos_x": 380,
                "pos_y": 140,
            },
            {
                "id": "eye_prism_dispersion",
                "name": "Refraction in Prism & Dispersion",
                "section": "10.3 - 10.4",
                "tier": 3,
                "description": "Triangular glass prism, angle of deviation, white light splitting into VIBGYOR, and natural rainbow formation.",
                "keywords": ["prism", "dispersion", "vibgyor", "spectrum", "angle of deviation", "rainbow", "internal reflection"],
                "pos_x": 650,
                "pos_y": 80,
            },
            {
                "id": "eye_atmospheric_scattering",
                "name": "Atmospheric Refraction & Scattering",
                "section": "10.5 - 10.6",
                "tier": 3,
                "description": "Twinkling of stars, early sunrise/delayed sunset, Tyndall effect, and Rayleigh scattering explaining blue sky.",
                "keywords": ["atmospheric refraction", "twinkling stars", "tyndall effect", "scattering", "blue sky", "red sunset"],
                "pos_x": 650,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "eye_anatomy_accommodation", "target": "eye_vision_defects", "relationship": "prerequisite"},
            {"source": "eye_anatomy_accommodation", "target": "eye_prism_dispersion", "relationship": "related"},
            {"source": "eye_prism_dispersion", "target": "eye_atmospheric_scattering", "relationship": "derived_from"},
        ],
    },

    "Electricity": {
        "class_level": 10,
        "chapter_number": 11,
        "nodes": [
            {
                "id": "elec_current_potential",
                "name": "Electric Current & Potential Difference",
                "section": "11.1 - 11.2",
                "tier": 1,
                "description": "Charge flow rate I = Q/t (Amperes) and work done per unit charge V = W/Q (Volts).",
                "keywords": ["electric current", "potential difference", "voltage", "charge", "ampere", "volt", "coulomb"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "elec_ohms_law",
                "name": "Ohm's Law & Resistance",
                "section": "11.3",
                "tier": 2,
                "description": "Direct proportionality V = IR at constant temperature, resistance definition, and I-V characteristic graphs.",
                "keywords": ["ohms law", "resistance", "v = ir", "resistor", "i-v graph", "ohmic"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "elec_resistivity_factors",
                "name": "Factors Affecting Resistance & Resistivity",
                "section": "11.4",
                "tier": 2,
                "description": "Dependence on length, area, temperature, and material resistivity R = rho * (L / A).",
                "keywords": ["resistivity", "resistance factors", "length", "cross sectional area", "rho", "ohm meter"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "elec_series_parallel",
                "name": "Resistors in Series & Parallel",
                "section": "11.5",
                "tier": 3,
                "description": "Equivalent resistance for series Rs = R1 + R2 and parallel 1/Rp = 1/R1 + 1/R2 combinations.",
                "keywords": ["series combination", "parallel combination", "equivalent resistance", "circuit analysis"],
                "pos_x": 620,
                "pos_y": 80,
            },
            {
                "id": "elec_heating_joules_law",
                "name": "Heating Effect & Joule's Law",
                "section": "11.6 - 11.7",
                "tier": 3,
                "description": "Heat generated H = I^2 * R * t, electric power P = VI = I^2*R = V^2/R, and commercial unit kWh.",
                "keywords": ["heating effect", "joules law", "electric power", "watt", "kilowatt hour", "fuse wire"],
                "pos_x": 620,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "elec_current_potential", "target": "elec_ohms_law", "relationship": "prerequisite"},
            {"source": "elec_current_potential", "target": "elec_resistivity_factors", "relationship": "prerequisite"},
            {"source": "elec_ohms_law", "target": "elec_series_parallel", "relationship": "derived_from"},
            {"source": "elec_ohms_law", "target": "elec_heating_joules_law", "relationship": "derived_from"},
            {"source": "elec_resistivity_factors", "target": "elec_series_parallel", "relationship": "related"},
        ],
    },

    "Magnetic Effects of Electric Current": {
        "class_level": 10,
        "chapter_number": 12,
        "nodes": [
            {
                "id": "mag_field_lines",
                "name": "Magnetic Field & Field Lines",
                "section": "12.1",
                "tier": 1,
                "description": "Compass needle deflection, magnetic field line properties, North-to-South continuous closed loops, and non-intersecting lines.",
                "keywords": ["magnetic field", "field lines", "compass", "magnetic poles", "closed loops"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "mag_current_conductors",
                "name": "Current-Carrying Conductors & Solenoid",
                "section": "12.2",
                "tier": 2,
                "description": "Right-Hand Thumb Rule, concentric circular field lines around straight wire, circular loop, and uniform field inside a solenoid.",
                "keywords": ["right hand thumb rule", "solenoid", "electromagnet", "circular loop", "magnetic strength"],
                "pos_x": 380,
                "pos_y": 140,
            },
            {
                "id": "mag_force_fleming_left",
                "name": "Force on Conductor & Fleming's Left Hand Rule",
                "section": "12.3",
                "tier": 3,
                "description": "Magnetic force on current-carrying wire F = BIl, Fleming's Left-Hand Rule (Thumb-Motion, Forefinger-Field, Center-Current).",
                "keywords": ["fleming left hand rule", "magnetic force", "motor principle", "perpendicular field"],
                "pos_x": 620,
                "pos_y": 80,
            },
            {
                "id": "mag_domestic_circuits",
                "name": "Domestic Circuits, Earthing & Fuse",
                "section": "12.4",
                "tier": 3,
                "description": "Live, neutral, and earth wires (220V), parallel appliance connection, short circuit prevention, and earth wire safety.",
                "keywords": ["domestic circuit", "earth wire", "fuse", "short circuit", "overloading", "live wire", "neutral wire"],
                "pos_x": 620,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "mag_field_lines", "target": "mag_current_conductors", "relationship": "prerequisite"},
            {"source": "mag_current_conductors", "target": "mag_force_fleming_left", "relationship": "derived_from"},
            {"source": "mag_current_conductors", "target": "mag_domestic_circuits", "relationship": "related"},
        ],
    },

    "Our Environment": {
        "class_level": 10,
        "chapter_number": 13,
        "nodes": [
            {
                "id": "env_ecosystem_components",
                "name": "Ecosystem & Biotic/Abiotic Factors",
                "section": "13.1",
                "tier": 1,
                "description": "Producers, consumers (herbivores, carnivores, omnivores), decomposers, and physical factors in natural and artificial ecosystems.",
                "keywords": ["ecosystem", "producers", "consumers", "decomposers", "biotic", "abiotic", "autotrophs"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "env_food_chains_energy_flow",
                "name": "Food Chains, Food Webs & 10% Law",
                "section": "13.1.1",
                "tier": 2,
                "description": "Trophic levels, unidirectional energy flow, Lindeman's 10% energy transfer rule, and ecological pyramids.",
                "keywords": ["food chain", "food web", "trophic level", "10 percent law", "energy flow", "biomass"],
                "pos_x": 380,
                "pos_y": 140,
            },
            {
                "id": "env_biomagnification_ozone",
                "name": "Biological Magnification & Ozone Depletion",
                "section": "13.2.1",
                "tier": 3,
                "description": "Pesticide accumulation in top trophic levels and O3 shield breakdown by chlorofluorocarbons (CFCs) with UV hazards.",
                "keywords": ["biological magnification", "ozone layer", "cfcs", "uv radiation", "ozone hole", "montreal protocol"],
                "pos_x": 650,
                "pos_y": 80,
            },
            {
                "id": "env_waste_management",
                "name": "Biodegradable Waste & Management",
                "section": "13.2.2",
                "tier": 3,
                "description": "Enzyme specificity, biodegradable vs non-biodegradable plastics, composting, landfills, and recycling.",
                "keywords": ["biodegradable", "non-biodegradable", "waste management", "recycling", "landfill", "composting"],
                "pos_x": 650,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "env_ecosystem_components", "target": "env_food_chains_energy_flow", "relationship": "prerequisite"},
            {"source": "env_food_chains_energy_flow", "target": "env_biomagnification_ozone", "relationship": "derived_from"},
            {"source": "env_ecosystem_components", "target": "env_waste_management", "relationship": "related"},
        ],
    },

    # =========================================================================
    # CLASS 9 NCERT SCIENCE CHAPTERS
    # =========================================================================
    "Describing Motion Around Us": {
        "class_level": 9,
        "chapter_number": 4,
        "nodes": [
            {
                "id": "mot_distance_displacement",
                "name": "Distance & Displacement",
                "section": "4.1",
                "tier": 1,
                "description": "Reference points, scalar path length (distance) vs vector shortest distance (displacement).",
                "keywords": ["distance", "displacement", "reference point", "scalar", "vector"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "mot_speed_velocity_acceleration",
                "name": "Speed, Velocity & Acceleration",
                "section": "4.2",
                "tier": 2,
                "description": "Uniform vs non-uniform motion, average speed, velocity with direction, and acceleration a = (v - u)/t.",
                "keywords": ["speed", "velocity", "acceleration", "uniform motion", "non-uniform"],
                "pos_x": 380,
                "pos_y": 140,
            },
            {
                "id": "mot_equations_graphs",
                "name": "Equations of Motion & Graphs",
                "section": "4.3 - 4.4",
                "tier": 3,
                "description": "Distance-time and velocity-time graphs, derivation of v = u + at, s = ut + 1/2at^2, and v^2 - u^2 = 2as.",
                "keywords": ["equations of motion", "velocity time graph", "v = u + at", "slope", "area under curve"],
                "pos_x": 650,
                "pos_y": 80,
            },
            {
                "id": "mot_uniform_circular",
                "name": "Uniform Circular Motion",
                "section": "4.5",
                "tier": 3,
                "description": "Constant speed with continuous direction change along circular path v = 2*pi*r / t (accelerated motion).",
                "keywords": ["uniform circular motion", "circular path", "centripetal", "constant speed"],
                "pos_x": 650,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "mot_distance_displacement", "target": "mot_speed_velocity_acceleration", "relationship": "prerequisite"},
            {"source": "mot_speed_velocity_acceleration", "target": "mot_equations_graphs", "relationship": "derived_from"},
            {"source": "mot_speed_velocity_acceleration", "target": "mot_uniform_circular", "relationship": "derived_from"},
        ],
    },

    "How Forces Affect Motion": {
        "class_level": 9,
        "chapter_number": 6,
        "nodes": [
            {
                "id": "force_balanced_unbalanced",
                "name": "Balanced & Unbalanced Forces",
                "section": "6.1",
                "tier": 1,
                "description": "Net zero force vs resultant force producing acceleration and changing state of motion.",
                "keywords": ["force", "balanced force", "unbalanced force", "resultant", "frictional force"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "force_newton_first_inertia",
                "name": "Newton's 1st Law & Inertia",
                "section": "6.2",
                "tier": 2,
                "description": "Inertia of rest, motion, and direction; mass as measure of inertia; Galileo's inclined plane experiment.",
                "keywords": ["first law", "inertia", "galileo", "mass", "state of rest"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "force_newton_second_momentum",
                "name": "Newton's 2nd Law & Momentum",
                "section": "6.3",
                "tier": 2,
                "description": "Linear momentum p = mv, rate of change of momentum, and mathematical force derivation F = ma (Newtons).",
                "keywords": ["second law", "momentum", "f = ma", "impulse", "rate of change of momentum"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "force_newton_third_conservation",
                "name": "Newton's 3rd Law & Momentum Conservation",
                "section": "6.4 - 6.5",
                "tier": 3,
                "description": "Equal and opposite action-reaction pairs and total momentum conservation in collisions m1u1 + m2u2 = m1v1 + m2v2.",
                "keywords": ["third law", "action reaction", "conservation of momentum", "recoil of gun", "collision"],
                "pos_x": 650,
                "pos_y": 160,
            },
        ],
        "edges": [
            {"source": "force_balanced_unbalanced", "target": "force_newton_first_inertia", "relationship": "prerequisite"},
            {"source": "force_balanced_unbalanced", "target": "force_newton_second_momentum", "relationship": "prerequisite"},
            {"source": "force_newton_second_momentum", "target": "force_newton_third_conservation", "relationship": "derived_from"},
            {"source": "force_newton_first_inertia", "target": "force_newton_third_conservation", "relationship": "related"},
        ],
    },

    "Work, Energy, and Simple Machines": {
        "class_level": 9,
        "chapter_number": 7,
        "nodes": [
            {
                "id": "work_definition_joules",
                "name": "Scientific Work & Joules",
                "section": "7.1",
                "tier": 1,
                "description": "Work done W = F * s in direction of force; positive, negative, and zero work.",
                "keywords": ["work", "joule", "force and displacement", "positive work", "negative work", "zero work"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "energy_kinetic_potential",
                "name": "Kinetic & Potential Energy",
                "section": "7.2",
                "tier": 2,
                "description": "Kinetic energy Ek = 1/2*m*v^2 and gravitational potential energy Ep = m*g*h.",
                "keywords": ["kinetic energy", "potential energy", "1/2mv^2", "mgh", "mechanical energy"],
                "pos_x": 380,
                "pos_y": 140,
            },
            {
                "id": "energy_conservation_law",
                "name": "Law of Conservation of Energy",
                "section": "7.3",
                "tier": 3,
                "description": "Transformation of energy, total mechanical energy constancy Ek + Ep = constant during free fall.",
                "keywords": ["conservation of energy", "energy transformation", "free fall", "mechanical energy constant"],
                "pos_x": 650,
                "pos_y": 80,
            },
            {
                "id": "work_power_commercial_unit",
                "name": "Rate of Doing Work (Power)",
                "section": "7.4",
                "tier": 3,
                "description": "Power P = W / t (Watts) and commercial electricity units (1 kWh = 3.6 x 10^6 J).",
                "keywords": ["power", "watt", "kilowatt", "commercial unit", "rate of doing work"],
                "pos_x": 650,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "work_definition_joules", "target": "energy_kinetic_potential", "relationship": "prerequisite"},
            {"source": "energy_kinetic_potential", "target": "energy_conservation_law", "relationship": "derived_from"},
            {"source": "work_definition_joules", "target": "work_power_commercial_unit", "relationship": "derived_from"},
        ],
    },

    "Cell: The Building Block of Life": {
        "class_level": 9,
        "chapter_number": 2,
        "nodes": [
            {
                "id": "cell_plasma_membrane",
                "name": "Plasma Membrane, Diffusion & Osmosis",
                "section": "2.1 - 2.2",
                "tier": 1,
                "description": "Selective permeability, lipid bilayer, diffusion, hypotonic/isotonic/hypertonic osmosis, and endocytosis.",
                "keywords": ["plasma membrane", "diffusion", "osmosis", "hypotonic", "hypertonic", "selective permeability"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "cell_nucleus_cytoplasm",
                "name": "Nucleus, Chromosomes & Prokaryotes",
                "section": "2.3",
                "tier": 2,
                "description": "Nuclear membrane, chromatin material, DNA genes, and prokaryotic (nucleoid) vs eukaryotic cell contrast.",
                "keywords": ["nucleus", "prokaryote", "eukaryote", "chromatin", "nucleoid", "dna"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "cell_organelles_functions",
                "name": "Cell Organelles (ER, Golgi, Lysosomes)",
                "section": "2.4",
                "tier": 3,
                "description": "Endoplasmic reticulum (RER/SER), Golgi packaging, suicide bags (lysosomes), and mitochondria ATP powerhouses.",
                "keywords": ["endoplasmic reticulum", "golgi apparatus", "lysosome", "mitochondria", "atp", "organelles"],
                "pos_x": 650,
                "pos_y": 80,
            },
            {
                "id": "cell_plant_plastids_vacuoles",
                "name": "Plastids, Vacuoles & Cell Wall",
                "section": "2.5",
                "tier": 3,
                "description": "Chloroplasts (photosynthesis), leucoplasts/chromoplasts, large plant central vacuole turgidity, and cellulose wall.",
                "keywords": ["plastids", "chloroplast", "vacuole", "cell wall", "cellulose", "turgidity", "plant cell"],
                "pos_x": 650,
                "pos_y": 240,
            },
        ],
        "edges": [
            {"source": "cell_plasma_membrane", "target": "cell_nucleus_cytoplasm", "relationship": "prerequisite"},
            {"source": "cell_nucleus_cytoplasm", "target": "cell_organelles_functions", "relationship": "derived_from"},
            {"source": "cell_plasma_membrane", "target": "cell_plant_plastids_vacuoles", "relationship": "related"},
            {"source": "cell_organelles_functions", "target": "cell_plant_plastids_vacuoles", "relationship": "related"},
        ],
    },

    "Tissues in Action": {
        "class_level": 9,
        "chapter_number": 3,
        "nodes": [
            {
                "id": "tissue_meristematic",
                "name": "Meristematic Plant Tissues",
                "section": "3.1",
                "tier": 1,
                "description": "Apical (length growth), intercalary (nodes), and lateral (cambium girth) actively dividing plant meristems.",
                "keywords": ["meristematic", "apical meristem", "lateral meristem", "intercalary", "cambium", "plant growth"],
                "pos_x": 150,
                "pos_y": 140,
            },
            {
                "id": "tissue_permanent_plant",
                "name": "Simple & Complex Permanent Tissues",
                "section": "3.2",
                "tier": 2,
                "description": "Parenchyma, collenchyma, sclerenchyma (lignin fibers), and complex vascular bundles (xylem and phloem).",
                "keywords": ["parenchyma", "collenchyma", "sclerenchyma", "lignin", "xylem", "phloem", "vascular bundle"],
                "pos_x": 380,
                "pos_y": 80,
            },
            {
                "id": "tissue_animal_epithelial_muscular",
                "name": "Epithelial & Muscular Animal Tissues",
                "section": "3.3.1 - 3.3.3",
                "tier": 2,
                "description": "Squamous, cuboidal, columnar, ciliated epithelium, and striated/smooth/cardiac muscle fibers.",
                "keywords": ["epithelial", "squamous", "ciliated", "striated muscle", "smooth muscle", "cardiac muscle"],
                "pos_x": 380,
                "pos_y": 240,
            },
            {
                "id": "tissue_connective_nervous",
                "name": "Connective & Nervous Tissues",
                "section": "3.3.2 - 3.3.4",
                "tier": 3,
                "description": "Blood, bone, cartilage, ligament, tendon, adipose fat storage, and neurons transmitting electrical impulses.",
                "keywords": ["connective tissue", "blood", "bone", "cartilage", "ligament", "tendon", "adipose", "neuron"],
                "pos_x": 650,
                "pos_y": 160,
            },
        ],
        "edges": [
            {"source": "tissue_meristematic", "target": "tissue_permanent_plant", "relationship": "derived_from"},
            {"source": "tissue_meristematic", "target": "tissue_animal_epithelial_muscular", "relationship": "related"},
            {"source": "tissue_animal_epithelial_muscular", "target": "tissue_connective_nervous", "relationship": "prerequisite"},
            {"source": "tissue_permanent_plant", "target": "tissue_connective_nervous", "relationship": "related"},
        ],
    },

    # =========================================================================
    # CLASS 10 NCERT MATHEMATICS CHAPTERS
    # =========================================================================
    "Real Numbers": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 1,
        "nodes": [
            {
                "id": "math10_euclid_fundamental",
                "name": "Fundamental Theorem of Arithmetic",
                "section": "1.2",
                "tier": 1,
                "description": "Prime factorisation uniqueness, HCF and LCM calculations, and prime decomposition of composite numbers.",
                "keywords": ["fundamental theorem", "prime factorisation", "composite numbers", "hcf", "lcm", "product of primes"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_irrational_proofs",
                "name": "Irrationality Proofs (√2, √3, √5)",
                "section": "1.3",
                "tier": 2,
                "description": "Proof of irrationality by contradiction for square roots of primes and linear combinations (a ± b√p).",
                "keywords": ["irrational number", "proof by contradiction", "co-prime", "divisibility", "root 2", "root 3", "root 5"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_decimal_expansions",
                "name": "Rational Decimal Expansions",
                "section": "1.4",
                "tier": 3,
                "description": "Terminating and non-terminating recurring decimal conditions based on denominator prime factorisation 2^n * 5^m.",
                "keywords": ["terminating decimal", "non-terminating recurring", "rational number", "denominator", "2^n 5^m"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_euclid_fundamental", "target": "math10_irrational_proofs", "relationship": "prerequisite"},
            {"source": "math10_euclid_fundamental", "target": "math10_decimal_expansions", "relationship": "prerequisite"},
        ],
    },

    "Polynomials": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 2,
        "nodes": [
            {
                "id": "math10_poly_zeros_geom",
                "name": "Geometric Meaning of Zeroes",
                "section": "2.2",
                "tier": 1,
                "description": "Relationship between x-intercepts of parabola / curves and number of real zeroes of linear, quadratic, and cubic polynomials.",
                "keywords": ["zeroes", "x-intercept", "parabola", "linear polynomial", "quadratic polynomial", "cubic polynomial"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_poly_coeff_relations",
                "name": "Zeroes & Coefficients Relationship",
                "section": "2.3",
                "tier": 2,
                "description": "Sum of zeroes (α + β = -b/a) and product of zeroes (αβ = c/a) for quadratic and cubic polynomials.",
                "keywords": ["sum of zeroes", "product of zeroes", "coefficients", "quadratic polynomial", "alpha beta"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_poly_division_alg",
                "name": "Division Algorithm for Polynomials",
                "section": "2.4",
                "tier": 3,
                "description": "Dividing polynomials p(x) = g(x)q(x) + r(x) to find remaining zeroes from known roots.",
                "keywords": ["division algorithm", "quotient", "remainder", "finding remaining zeroes", "factorisation"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_poly_zeros_geom", "target": "math10_poly_coeff_relations", "relationship": "prerequisite"},
            {"source": "math10_poly_coeff_relations", "target": "math10_poly_division_alg", "relationship": "derived_from"},
        ],
    },

    "Pair of Linear Equations in Two Variables": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 3,
        "nodes": [
            {
                "id": "math10_linear_graphical",
                "name": "Graphical Method & Consistency",
                "section": "3.2",
                "tier": 1,
                "description": "Intersecting, parallel, and coincident lines with consistency ratios a1/a2, b1/b2, c1/c2.",
                "keywords": ["graphical method", "intersecting lines", "parallel lines", "coincident", "consistent", "inconsistent"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_linear_substitution",
                "name": "Substitution & Elimination Methods",
                "section": "3.3",
                "tier": 2,
                "description": "Algebraic solution by substituting one variable or eliminating coefficients to solve simultaneous equations.",
                "keywords": ["substitution method", "elimination method", "algebraic solution", "simultaneous equations"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_linear_reducible",
                "name": "Equations Reducible to Linear Form",
                "section": "3.4",
                "tier": 3,
                "description": "Transforming non-linear paired fractions (e.g. 1/x, 1/y) into standard linear form using variable substitution.",
                "keywords": ["reducible equations", "upstream downstream", "speed time distance", "variable substitution"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_linear_graphical", "target": "math10_linear_substitution", "relationship": "prerequisite"},
            {"source": "math10_linear_substitution", "target": "math10_linear_reducible", "relationship": "related"},
        ],
    },

    "Quadratic Equations": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 4,
        "nodes": [
            {
                "id": "math10_quad_standard_factorisation",
                "name": "Standard Form & Factorisation",
                "section": "4.1 - 4.2",
                "tier": 1,
                "description": "ax^2 + bx + c = 0 formulation and solving by splitting the middle term.",
                "keywords": ["quadratic equation", "standard form", "factorisation", "splitting middle term", "roots"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_quad_formula",
                "name": "Quadratic Formula (Sridharacharya)",
                "section": "4.3",
                "tier": 2,
                "description": "Derivation and application of x = (-b ± √(b^2 - 4ac)) / (2a) for solving quadratic equations.",
                "keywords": ["quadratic formula", "completing square", "roots formula", "sridharacharya"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_quad_nature_roots",
                "name": "Discriminant & Nature of Roots",
                "section": "4.4",
                "tier": 3,
                "description": "D = b^2 - 4ac test: two distinct real roots (D > 0), two equal real roots (D = 0), or no real roots (D < 0).",
                "keywords": ["discriminant", "nature of roots", "equal roots", "distinct roots", "real roots"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_quad_standard_factorisation", "target": "math10_quad_formula", "relationship": "prerequisite"},
            {"source": "math10_quad_formula", "target": "math10_quad_nature_roots", "relationship": "derived_from"},
        ],
    },

    "Arithmetic Progressions": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 5,
        "nodes": [
            {
                "id": "math10_ap_definition_common_diff",
                "name": "AP Concept & Common Difference",
                "section": "5.1 - 5.2",
                "tier": 1,
                "description": "Definition of arithmetic progression, first term a, and common difference d = a_(k+1) - a_k.",
                "keywords": ["arithmetic progression", "first term", "common difference", "finite ap", "infinite ap"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_ap_nth_term",
                "name": "nth Term of an AP (a_n = a + (n-1)d)",
                "section": "5.3",
                "tier": 2,
                "description": "Calculating general nth term, finding position of terms, and solving unknown parameters.",
                "keywords": ["nth term", "general term", "a_n formula", "term from end"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_ap_sum_terms",
                "name": "Sum of First n Terms (S_n)",
                "section": "5.4",
                "tier": 3,
                "description": "Sum formulas S_n = n/2 [2a + (n-1)d] and S_n = n/2 (a + l) applied to word problems and series.",
                "keywords": ["sum of ap", "S_n formula", "sum of first n terms", "first n natural numbers"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_ap_definition_common_diff", "target": "math10_ap_nth_term", "relationship": "prerequisite"},
            {"source": "math10_ap_nth_term", "target": "math10_ap_sum_terms", "relationship": "derived_from"},
        ],
    },

    "Triangles": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 6,
        "nodes": [
            {
                "id": "math10_tri_similar_figures_bpt",
                "name": "Similar Figures & Basic Proportionality",
                "section": "6.1 - 6.2",
                "tier": 1,
                "description": "Similarity of geometric figures and Thales Theorem (BPT) with its converse.",
                "keywords": ["similarity", "basic proportionality theorem", "thales theorem", "ratio of sides"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_tri_similarity_criteria",
                "name": "Criteria for Similarity (AAA, SSS, SAS)",
                "section": "6.3",
                "tier": 2,
                "description": "Proof and application of AAA (or AA), SSS, and SAS similarity criteria for triangle pairs.",
                "keywords": ["similarity criteria", "AAA similarity", "AA criterion", "SSS similarity", "SAS similarity"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_tri_areas_pythagoras",
                "name": "Areas of Similar Triangles & Pythagoras",
                "section": "6.4 - 6.5",
                "tier": 3,
                "description": "Ratio of areas equal to ratio of squares of corresponding sides, and Pythagoras theorem proof and converse.",
                "keywords": ["areas of similar triangles", "pythagoras theorem", "hypotenuse", "right triangle"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_tri_similar_figures_bpt", "target": "math10_tri_similarity_criteria", "relationship": "prerequisite"},
            {"source": "math10_tri_similarity_criteria", "target": "math10_tri_areas_pythagoras", "relationship": "derived_from"},
        ],
    },

    "Coordinate Geometry": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 7,
        "nodes": [
            {
                "id": "math10_coord_distance_formula",
                "name": "Distance Formula",
                "section": "7.2",
                "tier": 1,
                "description": "Euclidean distance between two coordinates d = √((x2-x1)^2 + (y2-y1)^2) and collinearity tests.",
                "keywords": ["distance formula", "collinear points", "equidistant", "coordinates"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_coord_section_formula",
                "name": "Section Formula & Mid-Point",
                "section": "7.3",
                "tier": 2,
                "description": "Internal division of line segment in ratio m1:m2, midpoint formula, and trisection.",
                "keywords": ["section formula", "ratio division", "midpoint formula", "centroid", "trisection"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_coord_area_triangle",
                "name": "Area of a Triangle from Coordinates",
                "section": "7.4",
                "tier": 3,
                "description": "Calculating triangle area Area = 1/2 |x1(y2-y3) + x2(y3-y1) + x3(y1-y2)| and checking collinearity.",
                "keywords": ["area of triangle", "collinear test", "vertices coordinates"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_coord_distance_formula", "target": "math10_coord_section_formula", "relationship": "prerequisite"},
            {"source": "math10_coord_section_formula", "target": "math10_coord_area_triangle", "relationship": "related"},
        ],
    },

    "Introduction to Trigonometry": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 8,
        "nodes": [
            {
                "id": "math10_trig_ratios_def",
                "name": "Trigonometric Ratios (sin, cos, tan, cosec, sec, cot)",
                "section": "8.2",
                "tier": 1,
                "description": "Definitions of trigonometric ratios in a right-angled triangle relative to acute angles.",
                "keywords": ["trigonometric ratios", "sin", "cos", "tan", "cosec", "sec", "cot", "opposite adjacent hypotenuse"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_trig_specific_angles",
                "name": "Ratios of Specific Angles (0°, 30°, 45°, 60°, 90°)",
                "section": "8.3",
                "tier": 2,
                "description": "Standard values table and evaluations of trigonometric expressions.",
                "keywords": ["specific angles", "trig table", "sin 30", "cos 60", "tan 45", "evaluations"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_trig_identities",
                "name": "Trigonometric Identities (sin^2θ + cos^2θ = 1)",
                "section": "8.5",
                "tier": 3,
                "description": "Fundamental identities: sin^2 + cos^2 = 1, 1 + tan^2 = sec^2, 1 + cot^2 = cosec^2, and proofs.",
                "keywords": ["trigonometric identities", "proving identities", "sin^2 cos^2", "sec^2 tan^2", "cosec^2 cot^2"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_trig_ratios_def", "target": "math10_trig_specific_angles", "relationship": "prerequisite"},
            {"source": "math10_trig_specific_angles", "target": "math10_trig_identities", "relationship": "derived_from"},
        ],
    },

    "Some Applications of Trigonometry": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 9,
        "nodes": [
            {
                "id": "math10_trig_app_elevation_depression",
                "name": "Angles of Elevation & Depression",
                "section": "9.1",
                "tier": 1,
                "description": "Line of sight, horizontal line, angle of elevation (looking up), and angle of depression (looking down).",
                "keywords": ["angle of elevation", "angle of depression", "line of sight", "horizontal observer"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math10_trig_app_heights_distances",
                "name": "Solving Heights and Distances Problems",
                "section": "9.1.2",
                "tier": 2,
                "description": "Multi-step trigonometric calculations to find heights of towers, trees, buildings, and widths of rivers.",
                "keywords": ["heights and distances", "tower height", "shadow length", "two angles", "river width"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_trig_app_elevation_depression", "target": "math10_trig_app_heights_distances", "relationship": "prerequisite"},
        ],
    },

    "Circles": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 10,
        "nodes": [
            {
                "id": "math10_circ_tangent_radius_perp",
                "name": "Tangent & Radius Perpendicularity",
                "section": "10.2",
                "tier": 1,
                "description": "The tangent at any point of a circle is perpendicular to the radius through the point of contact (Theorem 10.1).",
                "keywords": ["tangent to circle", "point of contact", "radius perpendicular to tangent", "secant"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math10_circ_tangents_external_point",
                "name": "Length of Tangents from External Point",
                "section": "10.3",
                "tier": 2,
                "description": "The lengths of tangents drawn from an external point to a circle are equal (Theorem 10.2) and related angle properties.",
                "keywords": ["external point tangents", "equal tangents", "theorem 10.2", "circumscribing quadrilateral"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_circ_tangent_radius_perp", "target": "math10_circ_tangents_external_point", "relationship": "prerequisite"},
        ],
    },

    "Areas Related to Circles": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 11,
        "nodes": [
            {
                "id": "math10_area_circ_sector_segment",
                "name": "Sector & Segment of a Circle",
                "section": "11.1 - 11.2",
                "tier": 1,
                "description": "Area of sector (θ/360 * πr^2), length of an arc (θ/360 * 2πr), and area of minor/major segments.",
                "keywords": ["area of sector", "length of arc", "segment of circle", "minor sector", "major sector"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math10_area_circ_plane_combinations",
                "name": "Combinations of Plane Figures",
                "section": "11.3",
                "tier": 2,
                "description": "Finding shaded region areas composed of circles, semi-circles, squares, rectangles, and triangles.",
                "keywords": ["combinations of plane figures", "shaded region", "concentric circles", "designs"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_area_circ_sector_segment", "target": "math10_area_circ_plane_combinations", "relationship": "derived_from"},
        ],
    },

    "Surface Areas and Volumes": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 12,
        "nodes": [
            {
                "id": "math10_sa_volume_combination_solids",
                "name": "Surface Area & Volume of Combined Solids",
                "section": "12.2 - 12.3",
                "tier": 1,
                "description": "Total surface area and volume of combined 3D shapes: cylinder, cone, hemisphere, cuboid, and sphere.",
                "keywords": ["combined solids", "surface area", "volume of solids", "hemisphere cylinder cone", "toy shape"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math10_sa_volume_conversion_solids",
                "name": "Conversion of Solids & Melted Shapes",
                "section": "12.4",
                "tier": 2,
                "description": "Molding and casting solids: volume conservation when melting one solid shape into one or many new shapes.",
                "keywords": ["conversion of solids", "volume conservation", "melting casting", "embankment", "sphere to wire"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_sa_volume_combination_solids", "target": "math10_sa_volume_conversion_solids", "relationship": "related"},
        ],
    },

    "Statistics": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 13,
        "nodes": [
            {
                "id": "math10_stat_mean_grouped",
                "name": "Mean of Grouped Data (Direct, Assumed, Step Dev)",
                "section": "13.2",
                "tier": 1,
                "description": "Methods to calculate arithmetic mean: direct method (Σfi*xi / Σfi), assumed mean, and step deviation.",
                "keywords": ["mean of grouped data", "class mark", "direct method", "assumed mean", "step deviation"],
                "pos_x": 160,
                "pos_y": 140,
            },
            {
                "id": "math10_stat_mode_grouped",
                "name": "Mode of Grouped Data",
                "section": "13.3",
                "tier": 2,
                "description": "Modal class identification and mode formula Mode = l + [(f1 - f0) / (2f1 - f0 - f2)] * h.",
                "keywords": ["mode of grouped data", "modal class", "modal frequency", "mode formula"],
                "pos_x": 420,
                "pos_y": 140,
            },
            {
                "id": "math10_stat_median_grouped",
                "name": "Median of Grouped Data & Empirical Relation",
                "section": "13.4",
                "tier": 3,
                "description": "Cumulative frequency table, median formula Median = l + [(n/2 - cf)/f] * h, and 3 Median = Mode + 2 Mean.",
                "keywords": ["median of grouped data", "cumulative frequency", "median class", "empirical relationship"],
                "pos_x": 680,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_stat_mean_grouped", "target": "math10_stat_mode_grouped", "relationship": "related"},
            {"source": "math10_stat_mode_grouped", "target": "math10_stat_median_grouped", "relationship": "related"},
        ],
    },

    "Probability": {
        "class_level": 10,
        "subject": "Mathematics",
        "chapter_number": 14,
        "nodes": [
            {
                "id": "math10_prob_classical_definition",
                "name": "Classical Theoretical Probability (P(E))",
                "section": "14.1",
                "tier": 1,
                "description": "P(E) = (Number of outcomes favourable to E) / (Number of all possible outcomes), equally likely outcomes.",
                "keywords": ["probability", "theoretical probability", "favourable outcomes", "sample space", "equally likely"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math10_prob_complementary_experiments",
                "name": "Complementary Events & Standard Experiments",
                "section": "14.2",
                "tier": 2,
                "description": "P(E) + P(not E) = 1, impossible events (P = 0), sure events (P = 1), coin tosses, dice rolls, and 52-card deck.",
                "keywords": ["complementary event", "impossible event", "sure event", "deck of cards", "dice", "coins"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math10_prob_classical_definition", "target": "math10_prob_complementary_experiments", "relationship": "prerequisite"},
        ],
    },

    # =========================================================================
    # CLASS 9 NCERT MATHEMATICS CHAPTERS (GANITA MANJARI)
    # =========================================================================
    "Orienting Yourself: The Use of Coordinates": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 1,
        "nodes": [
            {
                "id": "math9_coord_cartesian_system",
                "name": "Cartesian Coordinate System & Axes",
                "section": "1.1",
                "tier": 1,
                "description": "Origin (0,0), X-axis (abscissa), Y-axis (ordinate), four quadrants, and positioning points.",
                "keywords": ["cartesian plane", "axes", "origin", "abscissa", "ordinate", "quadrants"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math9_coord_plotting_interpreting",
                "name": "Plotting Points & Map Grid Interpretation",
                "section": "1.2",
                "tier": 2,
                "description": "Locating ordered pairs (x, y) on grid paper and using coordinate frames to navigate spaces.",
                "keywords": ["plotting coordinates", "ordered pairs", "grid system", "mapping points"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math9_coord_cartesian_system", "target": "math9_coord_plotting_interpreting", "relationship": "prerequisite"},
        ],
    },

    "Introduction to Linear Polynomials": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 2,
        "nodes": [
            {
                "id": "math9_poly_terms_coefficients",
                "name": "Polynomial Terms & Degrees",
                "section": "2.1",
                "tier": 1,
                "description": "Monomials, binomials, trinomials, variables, coefficients, and degree of polynomials in one variable.",
                "keywords": ["polynomial terms", "coefficients", "monomial", "binomial", "degree of polynomial"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math9_poly_zeroes_linear_graphs",
                "name": "Zeroes of Linear Polynomials & Graphs",
                "section": "2.2 - 2.3",
                "tier": 2,
                "description": "Finding root/zero of ax + b = 0 and representing linear relations graphically as straight lines.",
                "keywords": ["zero of polynomial", "linear equation root", "straight line graph", "ax + b"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math9_poly_terms_coefficients", "target": "math9_poly_zeroes_linear_graphs", "relationship": "prerequisite"},
        ],
    },

    "The World of Numbers": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 3,
        "nodes": [
            {
                "id": "math9_num_real_number_types",
                "name": "Natural, Integers, Rationals & Irrationals",
                "section": "3.1",
                "tier": 1,
                "description": "Number classification: N, W, Z, Q, and irrational numbers (non-terminating non-recurring decimals).",
                "keywords": ["natural numbers", "integers", "rational numbers", "irrational numbers", "real numbers"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math9_num_line_and_exponents",
                "name": "Real Number Line & Laws of Exponents",
                "section": "3.2 - 3.3",
                "tier": 2,
                "description": "Locating roots on number line via Pythagoras and applying laws of exponents for positive real bases.",
                "keywords": ["number line", "representation of roots", "laws of exponents", "powers radicals"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math9_num_real_number_types", "target": "math9_num_line_and_exponents", "relationship": "prerequisite"},
        ],
    },

    "Exploring Algebraic Identities": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 4,
        "nodes": [
            {
                "id": "math9_alg_square_identities",
                "name": "Standard Square Identities",
                "section": "4.1",
                "tier": 1,
                "description": "(x + y)^2, (x - y)^2, (x^2 - y^2), and (x + a)(x + b) expansions and factorisations.",
                "keywords": ["algebraic identities", "square expansion", "difference of squares", "factorising quadratics"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math9_alg_cubic_factor_identities",
                "name": "Cubic Identities & Factor Theorem",
                "section": "4.2 - 4.3",
                "tier": 2,
                "description": "(x + y + z)^2, (x ± y)^3, and x^3 + y^3 + z^3 - 3xyz applications with remainder and factor theorems.",
                "keywords": ["cubic identities", "factor theorem", "remainder theorem", "polynomial factorisation"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math9_alg_square_identities", "target": "math9_alg_cubic_factor_identities", "relationship": "derived_from"},
        ],
    },

    "I'm Up and Down, and Round and Round": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 5,
        "nodes": [
            {
                "id": "math9_geom_lines_angles_parallel",
                "name": "Lines, Angles & Transversals",
                "section": "5.1 - 5.2",
                "tier": 1,
                "description": "Linear pair axiom, vertically opposite angles, and alternate/corresponding angles formed by transversals.",
                "keywords": ["lines and angles", "linear pair", "vertically opposite", "transversal", "alternate interior angles"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math9_geom_triangles_congruence",
                "name": "Triangle Congruence Criteria",
                "section": "5.3",
                "tier": 2,
                "description": "SAS, ASA, AAS, SSS, and RHS congruence rules and properties of isosceles triangles.",
                "keywords": ["congruence of triangles", "SAS criterion", "ASA criterion", "SSS criterion", "RHS congruence"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math9_geom_lines_angles_parallel", "target": "math9_geom_triangles_congruence", "relationship": "prerequisite"},
        ],
    },

    "Measuring Space: Perimeter and Area": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 6,
        "nodes": [
            {
                "id": "math9_mens_heron_formula",
                "name": "Heron's Formula for Triangles",
                "section": "6.1",
                "tier": 1,
                "description": "Calculating triangle area using semi-perimeter s = (a+b+c)/2 and Area = √(s(s-a)(s-b)(s-c)).",
                "keywords": ["heron formula", "semi perimeter", "triangle area", "scalene triangle"],
                "pos_x": 260,
                "pos_y": 140,
            },
            {
                "id": "math9_mens_surface_volume_basics",
                "name": "Surface Areas & Volumes of Solids",
                "section": "6.2 - 6.3",
                "tier": 2,
                "description": "Surface areas and volume formulas for cuboids, cubes, right circular cylinders, cones, and spheres.",
                "keywords": ["surface area", "volume", "cuboid", "cylinder", "cone", "sphere", "curved surface area"],
                "pos_x": 580,
                "pos_y": 140,
            },
        ],
        "edges": [
            {"source": "math9_mens_heron_formula", "target": "math9_mens_surface_volume_basics", "relationship": "related"},
        ],
    },

    "The Mathematics of Maybe: Introduction to Probability": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 7,
        "nodes": [
            {
                "id": "math9_prob_experimental_intro",
                "name": "Empirical & Experimental Probability",
                "section": "7.1 - 7.2",
                "tier": 1,
                "description": "Probability as a measure of chance: Number of trials in which event happened divided by total trials.",
                "keywords": ["experimental probability", "empirical probability", "trials", "frequency", "outcomes"],
                "pos_x": 420,
                "pos_y": 140,
            },
        ],
        "edges": [],
    },

    "Predicting What Comes Next: Exploring Sequences and Progressions": {
        "class_level": 9,
        "subject": "Mathematics",
        "chapter_number": 8,
        "nodes": [
            {
                "id": "math9_seq_patterns_progressions",
                "name": "Sequences & Progressions Foundations",
                "section": "8.1 - 8.3",
                "tier": 1,
                "description": "Identifying numerical patterns, recurrence relations, general terms, and linear progressions.",
                "keywords": ["sequences", "progressions", "number patterns", "general term", "recurrence"],
                "pos_x": 420,
                "pos_y": 140,
            },
        ],
        "edges": [],
    },
}


def get_chapter_concept_metadata(
    chapter_name: str, class_level: Optional[int] = None, subject: Optional[str] = None
) -> Optional[Dict[str, Any]]:
    """
    Retrieves the concept registry definition for a chapter.
    Matches by exact title or normalized substring, optionally filtered by class and subject.
    """
    clean_name = chapter_name.strip()
    subj_filter = str(subject).strip().lower() if subject else None

    if clean_name in CHAPTER_CONCEPTS_REGISTRY:
        data = CHAPTER_CONCEPTS_REGISTRY[clean_name]
        data_subj = str(data.get("subject", "Science")).lower()
        if (class_level is None or int(data["class_level"]) == int(class_level)) and (
            subj_filter is None or subj_filter in data_subj or data_subj in subj_filter
        ):
            return data

    # Fuzzy match by normalized lowercase
    target_lower = clean_name.lower().replace("–", "-").replace("—", "-").replace("'", "")
    for ch_title, data in CHAPTER_CONCEPTS_REGISTRY.items():
        ch_lower = ch_title.lower().replace("–", "-").replace("—", "-").replace("'", "")
        if target_lower in ch_lower or ch_lower in target_lower:
            data_subj = str(data.get("subject", "Science")).lower()
            if (class_level is None or int(data["class_level"]) == int(class_level)) and (
                subj_filter is None or subj_filter in data_subj or data_subj in subj_filter
            ):
                return data

    return None


def get_all_registered_chapters(
    class_level: Optional[int] = None, subject: Optional[str] = None
) -> List[Dict[str, Any]]:
    """Returns list of all chapters with registered concept graphs, filtered by class and subject."""
    chapters = []
    subj_filter = str(subject).strip().lower() if subject else None

    for ch_name, data in CHAPTER_CONCEPTS_REGISTRY.items():
        data_subj = str(data.get("subject", "Science")).lower()
        if class_level is not None and int(data["class_level"]) != int(class_level):
            continue
        if subj_filter is not None and not (subj_filter in data_subj or data_subj in subj_filter):
            continue

        chapters.append({
            "chapter": ch_name,
            "chapter_number": data["chapter_number"],
            "class_level": data["class_level"],
            "subject": data.get("subject", "Science"),
            "concept_count": len(data.get("nodes", [])),
            "edge_count": len(data.get("edges", [])),
        })
    return sorted(chapters, key=lambda x: (x["class_level"], x["subject"], x["chapter_number"]))
