# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking

LiteralString = str
# -- template engine/abstract.py.jinja --


from ._abstract import SyncAbstractEngine as AbstractEngine

__all__ = ('AbstractEngine',)
